project_id = "tvaouclllewfmxjuhfbq"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-business-email]
    verify_jwt = false
  [functions.send-weekly-summary]
    verify_jwt = true
  [functions.invite-user]
    verify_jwt = false
